name: edistrict_odisha
description: "e-District Odisha application for accessing government services."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  image_picker: ^1.1.2
  file_picker: ^10.3.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/oglogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/oglogo.png
    - assets/db/coverage_location.db
    - assets/db/lgd_master.db
    - assets/db/ric_master.db
